spring:
  application:
    name=auth-service
  datasource:
    url: jdbc:h2.mem:Kauthdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 18000000 # 5 horas

